version: '3'

networks:
  localhost:
    #name: my_network

volumes:
  MariaDB_data:
    # name: mariaDB
    # driver: bridge
    driver_opts:
      o: bind
      type: none
      device: /home/mdelwaul/data/mysql
  wordPressPHP_data:
    # name: wp
    # driver: bridge
    driver_opts:
      o: bind
      type: none
      device: /home/mdelwaul/data/wordpress

services:
  nginx:
    depends_on:
      - wordpress
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    networks:
      - localhost
    restart: unless-stopped
    volumes:
      - wordPressPHP_data:/var/www/wordpress
    build: ./requirements/nginx
  
  wordpress:
    image: wordpress
    container_name: wordpress
    networks:
      - localhost
    depends_on:
      - mariadb
    volumes:
      - wordPressPHP_data:/var/www/wordpress
    restart: unless-stopped
    environment:
      - ADMIN_USER=${ADMIN_USER_ENV}
      - ADMIN_PW=${ADMIN_PW_ENV}
      - USER_USER=${USER_USER_ENV}
      - USER_PW=${USER_PW_ENV}
      - ADMIN_email=${ADMIN_email_ENV}
    ports:
      - "9000:9000"
    build: ./requirements/wordPressPHP

  mariadb:
    image: mariadb
    container_name: mariadb
    networks:
      - localhost
    volumes:
      - MariaDB_data:/var/lib/mysql
    restart: unless-stopped
    expose:
      - "3306"
    build: ./requirements/MariaDB

